# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
description = "栃木県宇都宮市の「ひもろぎ音楽教室」は、バイオリン・ピアノ・幼児音感教育に対応した個人レッスン制の音楽教室です。見学随時受付中。音楽の楽しさを、ひとりひとりに丁寧に伝えています。"
keywords = ["ひもろぎ音楽教室","宇都宮 音楽教室","宇都宮 バイオリン教室","宇都宮 ピアノ教室","宇都宮 幼児音感教室","音楽 個人レッスン","子ども 音楽教室","音感教育 幼児","バイオリン 初心者","ピアノ 初心者","音楽教室 見学受付","音楽教育 宇都宮"]


images = ['site-feature-image.png']
# mainMenuLogo = "images/logo.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "ひもろぎ音楽教室"
footerAboutText = "栃木県宇都宮市の「ひもろぎ音楽教室」は、バイオリン・ピアノ・幼児音感教育に対応した個人レッスン制の音楽教室です。見学随時受付中。音楽の楽しさを、ひとりひとりに丁寧に伝えています。"

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = true
  listTagFilter = true
